---
title: "CM-annotated-bib"
author: "Michelle Stuart"
date: "2/27/2019"
output: github_document
bibliography: "/Users/michellestuart/Documents/genomics_pinskylab/clownfish_movement/references.bib"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(citr)
```

1. [@addis2013Implications] The purpose of this study was to determine the effectiveness of unreported artificial reefs as a haven for overfished reef fish.  They did this through tagging (mark recapture). They also tested factors affecting reef movement. This study is looking at fish movement in response to fishing pressure.  
1. [@davies1995Patterns] This is an 8 chapter thesis with a 5 page abstract.  I think each chapter can be treated as a separate paper for the purposes of this bibliography.  I’m skipping to ch 6 which appears to be the discussion of a long range reef fish movement study. The point is to gather quantitative information on the frequency of small scale movement within and among habitats:  
    + Among sites  
    + Among habitats within sites  
    + Within habitats.    
    They found that some but not all species of reef Fish are "capable of transversing over large expanses of open sand" in the case of are individual who moved ~ 400m.  They found that habitat of release affected movement and that fish hesitated to cross reef-sand boundaries 

1. [@williamsSpatialPatternsPopulation2003] This paper looked at large sale moment of reef fish-many
Km. Looked at reproductive parameters, growth mortality and finally large scale movement of post-settlement fish.

1. [@zeller2003Movements] This paper looked at export of fish from marine reserves, they found that most fish moved within a 50×30m area of original capture site. 2 species of the Same genus moved > 100m & <30m, Showing that movement is highly variable and not dependent on taxonomy. they Concluded that spillover is hard to detect.

1. [@williams2003Scales] This paper looked at age and growth through otoliths. Not relevant to movement study.  
1. [@zeller1997Home] Zeller 1997 -who cited this?  This paper looked at the home range and spatial use
of P. leopardus through telemetry and live tracking. They found that fish from reefs were less daring than fish from patch reefs and that all fish had a few  favorite spots that they visited regularly. 

1. [@russ1996marine] Russ 1996 This paper is examining spillover from marine reserves in the Philippines. they found that over time, there was an increase in the abundance of adults near the boundaries of the reserve.  

1. [@cowlishaw2014Determinants] Cowlishaw, 2014 This is a thesis about factors that determine home
range and territory size for coral reef fish. In Ch 2 they mention the ability to relocate after disturbance. Ch 3 looks at damselfish ability to home and territorial behavior. This might be of particular interest to our movement study. the largest home range belonged to an omnivorous damselfish.  

1. [@williams2010Exploring] Williams 2010 This paper describes a model designed to look at are
Species in are region in Australia. They designed the model because tagging wasn't working. (high mortality low recapture rates)

> References


