---
title: "Assign gen_ids to successfully sequenced fish"
output: html_notebook
---
This script re-assigns gen_ids to all fish that were successfully sequenced.
```{r setup, include=FALSE}
library(clownfish)
library(tidyverse)
library(here)
library(RMySQL)

# while db connection using helper file isn't working 
source("~/Documents/clownfish-pkg/R/db_connections.R")
leyte <- read_db("Leyte")
lab <- read_db("Laboratory")
```

# Get list of successfully sequenced sample_ids
- this comes from the most recent filtered genepop (still has regenos and recaptures in it)
```{r}
genotyped_ligs <- read_genepop(here("data", "seq03-33_identity", "seq33_03_baits_only_SNPs.gen")) %>% 
  mutate(ligation_id = str_extract(names, "L\\d+")) %>% 
  select(ligation_id)

genotyped_samples <- samp_from_lig(genotyped_ligs) %>% 
  select(sample_id) %>%  
  filter(grepl("APCL", sample_id)) %>% 
  distinct() %>% 
  arrange(sample_id) %>% 
  mutate(gen_id = 1:nrow(.))

saveRDS(genotyped_samples, here("data", "genotyped-samples.RData"))
```

# Go to the leyteBuildDB repo to write the new data to the database